[2022-08-29 16:20:01,061] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available scheduled__2022-08-28T00:00:00+00:00 [queued]>
[2022-08-29 16:20:01,072] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available scheduled__2022-08-28T00:00:00+00:00 [queued]>
[2022-08-29 16:20:01,072] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-08-29 16:20:01,072] {taskinstance.py:1357} INFO - Starting attempt 2 of 2
[2022-08-29 16:20:01,072] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-08-29 16:20:01,088] {taskinstance.py:1377} INFO - Executing <Task(HttpSensor): is_api_available> on 2022-08-28 00:00:00+00:00
[2022-08-29 16:20:01,095] {standard_task_runner.py:52} INFO - Started process 3249 to run task
[2022-08-29 16:20:01,100] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'is_api_available', 'scheduled__2022-08-28T00:00:00+00:00', '--job-id', '99', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmpfmhoeuid', '--error-file', '/tmp/tmpz43zofpl']
[2022-08-29 16:20:01,101] {standard_task_runner.py:80} INFO - Job 99: Subtask is_api_available
[2022-08-29 16:20:01,173] {task_command.py:369} INFO - Running <TaskInstance: user_processing.is_api_available scheduled__2022-08-28T00:00:00+00:00 [running]> on host 7f0ff65cfbf7
[2022-08-29 16:20:01,264] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=is_api_available
AIRFLOW_CTX_EXECUTION_DATE=2022-08-28T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-08-28T00:00:00+00:00
[2022-08-29 16:20:01,265] {http.py:97} INFO - Poking: api/
[2022-08-29 16:20:01,277] {base.py:68} INFO - Using connection ID 'user_api' for task execution.
[2022-08-29 16:20:01,279] {http.py:129} INFO - Sending 'GET' to url: https://randomuser.me/api/
[2022-08-29 16:20:01,473] {base.py:301} INFO - Success criteria met. Exiting.
[2022-08-29 16:20:01,492] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=is_api_available, execution_date=20220828T000000, start_date=20220829T162001, end_date=20220829T162001
[2022-08-29 16:20:01,513] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-08-29 16:20:01,582] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
