[2022-08-28 11:18:42,170] {processor.py:153} INFO - Started process (PID=8922) to work on /opt/airflow/dags/user1.py
[2022-08-28 11:18:42,170] {processor.py:641} INFO - Processing file /opt/airflow/dags/user1.py for tasks to queue
[2022-08-28 11:18:42,171] {logging_mixin.py:115} INFO - [2022-08-28 11:18:42,171] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/user1.py
[2022-08-28 11:18:42,185] {logging_mixin.py:115} INFO - [2022-08-28 11:18:42,184] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/user1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user1.py", line 18, in <module>
    '''
TypeError: 'module' object is not callable
[2022-08-28 11:18:42,186] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/user1.py
[2022-08-28 11:18:42,215] {processor.py:161} INFO - Processing /opt/airflow/dags/user1.py took 0.051 seconds
[2022-08-28 11:19:12,289] {processor.py:153} INFO - Started process (PID=8981) to work on /opt/airflow/dags/user1.py
[2022-08-28 11:19:12,315] {processor.py:641} INFO - Processing file /opt/airflow/dags/user1.py for tasks to queue
[2022-08-28 11:19:12,316] {logging_mixin.py:115} INFO - [2022-08-28 11:19:12,316] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/user1.py
[2022-08-28 11:19:12,336] {logging_mixin.py:115} INFO - [2022-08-28 11:19:12,334] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/user1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user1.py", line 18, in <module>
    '''
TypeError: 'module' object is not callable
[2022-08-28 11:19:12,336] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/user1.py
[2022-08-28 11:19:12,364] {processor.py:161} INFO - Processing /opt/airflow/dags/user1.py took 0.081 seconds
[2022-08-28 11:19:42,838] {processor.py:153} INFO - Started process (PID=9035) to work on /opt/airflow/dags/user1.py
[2022-08-28 11:19:42,839] {processor.py:641} INFO - Processing file /opt/airflow/dags/user1.py for tasks to queue
[2022-08-28 11:19:42,840] {logging_mixin.py:115} INFO - [2022-08-28 11:19:42,840] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/user1.py
[2022-08-28 11:19:42,853] {logging_mixin.py:115} INFO - [2022-08-28 11:19:42,852] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/user1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user1.py", line 18, in <module>
    '''
TypeError: 'module' object is not callable
[2022-08-28 11:19:42,854] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/user1.py
[2022-08-28 11:19:42,880] {processor.py:161} INFO - Processing /opt/airflow/dags/user1.py took 0.047 seconds
[2022-08-28 11:20:13,474] {processor.py:153} INFO - Started process (PID=9087) to work on /opt/airflow/dags/user1.py
[2022-08-28 11:20:13,476] {processor.py:641} INFO - Processing file /opt/airflow/dags/user1.py for tasks to queue
[2022-08-28 11:20:13,477] {logging_mixin.py:115} INFO - [2022-08-28 11:20:13,477] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/user1.py
[2022-08-28 11:20:13,494] {logging_mixin.py:115} INFO - [2022-08-28 11:20:13,493] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/user1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user1.py", line 18, in <module>
    '''
TypeError: 'module' object is not callable
[2022-08-28 11:20:13,494] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/user1.py
[2022-08-28 11:20:13,526] {processor.py:161} INFO - Processing /opt/airflow/dags/user1.py took 0.067 seconds
[2022-08-28 11:20:44,472] {processor.py:153} INFO - Started process (PID=9148) to work on /opt/airflow/dags/user1.py
[2022-08-28 11:20:44,473] {processor.py:641} INFO - Processing file /opt/airflow/dags/user1.py for tasks to queue
[2022-08-28 11:20:44,474] {logging_mixin.py:115} INFO - [2022-08-28 11:20:44,473] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/user1.py
[2022-08-28 11:20:44,488] {logging_mixin.py:115} INFO - [2022-08-28 11:20:44,487] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/user1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user1.py", line 18, in <module>
    '''
TypeError: 'module' object is not callable
[2022-08-28 11:20:44,488] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/user1.py
[2022-08-28 11:20:44,516] {processor.py:161} INFO - Processing /opt/airflow/dags/user1.py took 0.051 seconds
[2022-08-28 11:21:15,250] {processor.py:153} INFO - Started process (PID=9209) to work on /opt/airflow/dags/user1.py
[2022-08-28 11:21:15,251] {processor.py:641} INFO - Processing file /opt/airflow/dags/user1.py for tasks to queue
[2022-08-28 11:21:15,252] {logging_mixin.py:115} INFO - [2022-08-28 11:21:15,252] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/user1.py
[2022-08-28 11:21:15,266] {logging_mixin.py:115} INFO - [2022-08-28 11:21:15,265] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/user1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user1.py", line 18, in <module>
    '''
TypeError: 'module' object is not callable
[2022-08-28 11:21:15,266] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/user1.py
[2022-08-28 11:21:15,293] {processor.py:161} INFO - Processing /opt/airflow/dags/user1.py took 0.049 seconds
[2022-08-28 11:21:45,966] {processor.py:153} INFO - Started process (PID=9263) to work on /opt/airflow/dags/user1.py
[2022-08-28 11:21:45,966] {processor.py:641} INFO - Processing file /opt/airflow/dags/user1.py for tasks to queue
[2022-08-28 11:21:45,967] {logging_mixin.py:115} INFO - [2022-08-28 11:21:45,967] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/user1.py
[2022-08-28 11:21:45,982] {logging_mixin.py:115} INFO - [2022-08-28 11:21:45,981] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/user1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user1.py", line 18, in <module>
    '''
TypeError: 'module' object is not callable
[2022-08-28 11:21:45,982] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/user1.py
[2022-08-28 11:21:46,009] {processor.py:161} INFO - Processing /opt/airflow/dags/user1.py took 0.049 seconds
[2022-08-28 11:22:16,880] {processor.py:153} INFO - Started process (PID=9323) to work on /opt/airflow/dags/user1.py
[2022-08-28 11:22:16,901] {processor.py:641} INFO - Processing file /opt/airflow/dags/user1.py for tasks to queue
[2022-08-28 11:22:16,902] {logging_mixin.py:115} INFO - [2022-08-28 11:22:16,902] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/user1.py
[2022-08-28 11:22:16,916] {logging_mixin.py:115} INFO - [2022-08-28 11:22:16,915] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/user1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user1.py", line 18, in <module>
    '''
TypeError: 'module' object is not callable
[2022-08-28 11:22:16,916] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/user1.py
[2022-08-28 11:22:16,943] {processor.py:161} INFO - Processing /opt/airflow/dags/user1.py took 0.069 seconds
[2022-08-28 11:22:47,713] {processor.py:153} INFO - Started process (PID=9376) to work on /opt/airflow/dags/user1.py
[2022-08-28 11:22:47,714] {processor.py:641} INFO - Processing file /opt/airflow/dags/user1.py for tasks to queue
[2022-08-28 11:22:47,715] {logging_mixin.py:115} INFO - [2022-08-28 11:22:47,715] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/user1.py
[2022-08-28 11:22:47,730] {logging_mixin.py:115} INFO - [2022-08-28 11:22:47,729] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/user1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user1.py", line 18, in <module>
    '''
TypeError: 'module' object is not callable
[2022-08-28 11:22:47,731] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/user1.py
[2022-08-28 11:22:47,757] {processor.py:161} INFO - Processing /opt/airflow/dags/user1.py took 0.050 seconds
[2022-08-28 11:23:18,674] {processor.py:153} INFO - Started process (PID=9438) to work on /opt/airflow/dags/user1.py
[2022-08-28 11:23:18,676] {processor.py:641} INFO - Processing file /opt/airflow/dags/user1.py for tasks to queue
[2022-08-28 11:23:18,677] {logging_mixin.py:115} INFO - [2022-08-28 11:23:18,677] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/user1.py
[2022-08-28 11:23:18,690] {logging_mixin.py:115} INFO - [2022-08-28 11:23:18,689] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/user1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user1.py", line 18, in <module>
    '''
TypeError: 'module' object is not callable
[2022-08-28 11:23:18,691] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/user1.py
[2022-08-28 11:23:18,717] {processor.py:161} INFO - Processing /opt/airflow/dags/user1.py took 0.049 seconds
[2022-08-28 11:23:49,399] {processor.py:153} INFO - Started process (PID=9491) to work on /opt/airflow/dags/user1.py
[2022-08-28 11:23:49,416] {processor.py:641} INFO - Processing file /opt/airflow/dags/user1.py for tasks to queue
[2022-08-28 11:23:49,417] {logging_mixin.py:115} INFO - [2022-08-28 11:23:49,417] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/user1.py
[2022-08-28 11:23:49,431] {logging_mixin.py:115} INFO - [2022-08-28 11:23:49,430] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/user1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user1.py", line 18, in <module>
    '''
TypeError: 'module' object is not callable
[2022-08-28 11:23:49,431] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/user1.py
[2022-08-28 11:23:49,460] {processor.py:161} INFO - Processing /opt/airflow/dags/user1.py took 0.066 seconds
[2022-08-28 11:24:19,597] {processor.py:153} INFO - Started process (PID=9553) to work on /opt/airflow/dags/user1.py
[2022-08-28 11:24:19,598] {processor.py:641} INFO - Processing file /opt/airflow/dags/user1.py for tasks to queue
[2022-08-28 11:24:19,598] {logging_mixin.py:115} INFO - [2022-08-28 11:24:19,598] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/user1.py
[2022-08-28 11:24:19,614] {logging_mixin.py:115} INFO - [2022-08-28 11:24:19,613] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/user1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user1.py", line 18, in <module>
    '''
TypeError: 'module' object is not callable
[2022-08-28 11:24:19,614] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/user1.py
[2022-08-28 11:24:19,640] {processor.py:161} INFO - Processing /opt/airflow/dags/user1.py took 0.049 seconds
[2022-08-28 11:24:50,041] {processor.py:153} INFO - Started process (PID=9607) to work on /opt/airflow/dags/user1.py
[2022-08-28 11:24:50,057] {processor.py:641} INFO - Processing file /opt/airflow/dags/user1.py for tasks to queue
[2022-08-28 11:24:50,058] {logging_mixin.py:115} INFO - [2022-08-28 11:24:50,058] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/user1.py
[2022-08-28 11:24:50,072] {logging_mixin.py:115} INFO - [2022-08-28 11:24:50,071] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/user1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user1.py", line 18, in <module>
    '''
TypeError: 'module' object is not callable
[2022-08-28 11:24:50,073] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/user1.py
[2022-08-28 11:24:50,099] {processor.py:161} INFO - Processing /opt/airflow/dags/user1.py took 0.064 seconds
[2022-08-28 11:25:20,893] {processor.py:153} INFO - Started process (PID=9670) to work on /opt/airflow/dags/user1.py
[2022-08-28 11:25:20,894] {processor.py:641} INFO - Processing file /opt/airflow/dags/user1.py for tasks to queue
[2022-08-28 11:25:20,895] {logging_mixin.py:115} INFO - [2022-08-28 11:25:20,895] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/user1.py
[2022-08-28 11:25:20,909] {logging_mixin.py:115} INFO - [2022-08-28 11:25:20,908] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/user1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user1.py", line 18, in <module>
    '''
TypeError: 'module' object is not callable
[2022-08-28 11:25:20,910] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/user1.py
[2022-08-28 11:25:20,936] {processor.py:161} INFO - Processing /opt/airflow/dags/user1.py took 0.050 seconds
[2022-08-28 11:25:51,899] {processor.py:153} INFO - Started process (PID=9734) to work on /opt/airflow/dags/user1.py
[2022-08-28 11:25:51,913] {processor.py:641} INFO - Processing file /opt/airflow/dags/user1.py for tasks to queue
[2022-08-28 11:25:51,914] {logging_mixin.py:115} INFO - [2022-08-28 11:25:51,914] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/user1.py
[2022-08-28 11:25:51,932] {logging_mixin.py:115} INFO - [2022-08-28 11:25:51,931] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/user1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user1.py", line 18, in <module>
    '''
TypeError: 'module' object is not callable
[2022-08-28 11:25:51,932] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/user1.py
[2022-08-28 11:25:51,978] {processor.py:161} INFO - Processing /opt/airflow/dags/user1.py took 0.091 seconds
[2022-08-28 11:26:22,035] {processor.py:153} INFO - Started process (PID=9788) to work on /opt/airflow/dags/user1.py
[2022-08-28 11:26:22,036] {processor.py:641} INFO - Processing file /opt/airflow/dags/user1.py for tasks to queue
[2022-08-28 11:26:22,036] {logging_mixin.py:115} INFO - [2022-08-28 11:26:22,036] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/user1.py
[2022-08-28 11:26:22,050] {logging_mixin.py:115} INFO - [2022-08-28 11:26:22,050] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/user1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user1.py", line 18, in <module>
    '''
TypeError: 'module' object is not callable
[2022-08-28 11:26:22,051] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/user1.py
[2022-08-28 11:26:22,078] {processor.py:161} INFO - Processing /opt/airflow/dags/user1.py took 0.048 seconds
[2022-08-28 11:26:53,037] {processor.py:153} INFO - Started process (PID=9851) to work on /opt/airflow/dags/user1.py
[2022-08-28 11:26:53,038] {processor.py:641} INFO - Processing file /opt/airflow/dags/user1.py for tasks to queue
[2022-08-28 11:26:53,039] {logging_mixin.py:115} INFO - [2022-08-28 11:26:53,039] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/user1.py
[2022-08-28 11:26:53,057] {logging_mixin.py:115} INFO - [2022-08-28 11:26:53,056] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/user1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user1.py", line 18, in <module>
    '''
TypeError: 'module' object is not callable
[2022-08-28 11:26:53,057] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/user1.py
[2022-08-28 11:26:53,088] {processor.py:161} INFO - Processing /opt/airflow/dags/user1.py took 0.058 seconds
[2022-08-28 11:27:23,212] {processor.py:153} INFO - Started process (PID=9905) to work on /opt/airflow/dags/user1.py
[2022-08-28 11:27:23,213] {processor.py:641} INFO - Processing file /opt/airflow/dags/user1.py for tasks to queue
[2022-08-28 11:27:23,214] {logging_mixin.py:115} INFO - [2022-08-28 11:27:23,213] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/user1.py
[2022-08-28 11:27:23,230] {logging_mixin.py:115} INFO - [2022-08-28 11:27:23,229] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/user1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user1.py", line 18, in <module>
    '''
TypeError: 'module' object is not callable
[2022-08-28 11:27:23,230] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/user1.py
[2022-08-28 11:27:23,260] {processor.py:161} INFO - Processing /opt/airflow/dags/user1.py took 0.055 seconds
[2022-08-28 11:27:53,745] {processor.py:153} INFO - Started process (PID=9967) to work on /opt/airflow/dags/user1.py
[2022-08-28 11:27:53,747] {processor.py:641} INFO - Processing file /opt/airflow/dags/user1.py for tasks to queue
[2022-08-28 11:27:53,748] {logging_mixin.py:115} INFO - [2022-08-28 11:27:53,747] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/user1.py
[2022-08-28 11:27:53,782] {logging_mixin.py:115} INFO - [2022-08-28 11:27:53,780] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/user1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user1.py", line 18, in <module>
    '''
TypeError: 'module' object is not callable
[2022-08-28 11:27:53,782] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/user1.py
[2022-08-28 11:27:53,825] {processor.py:161} INFO - Processing /opt/airflow/dags/user1.py took 0.099 seconds
[2022-08-28 11:28:24,319] {processor.py:153} INFO - Started process (PID=10020) to work on /opt/airflow/dags/user1.py
[2022-08-28 11:28:24,320] {processor.py:641} INFO - Processing file /opt/airflow/dags/user1.py for tasks to queue
[2022-08-28 11:28:24,322] {logging_mixin.py:115} INFO - [2022-08-28 11:28:24,322] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/user1.py
[2022-08-28 11:28:24,341] {logging_mixin.py:115} INFO - [2022-08-28 11:28:24,339] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/user1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user1.py", line 18, in <module>
    '''
TypeError: 'module' object is not callable
[2022-08-28 11:28:24,341] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/user1.py
[2022-08-28 11:28:24,380] {processor.py:161} INFO - Processing /opt/airflow/dags/user1.py took 0.068 seconds
[2022-08-28 11:28:54,904] {processor.py:153} INFO - Started process (PID=10073) to work on /opt/airflow/dags/user1.py
[2022-08-28 11:28:54,923] {processor.py:641} INFO - Processing file /opt/airflow/dags/user1.py for tasks to queue
[2022-08-28 11:28:54,924] {logging_mixin.py:115} INFO - [2022-08-28 11:28:54,924] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/user1.py
[2022-08-28 11:28:54,938] {logging_mixin.py:115} INFO - [2022-08-28 11:28:54,936] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/user1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user1.py", line 18, in <module>
    '''
TypeError: 'module' object is not callable
[2022-08-28 11:28:54,938] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/user1.py
[2022-08-28 11:28:54,965] {processor.py:161} INFO - Processing /opt/airflow/dags/user1.py took 0.066 seconds
[2022-08-28 11:29:25,252] {processor.py:153} INFO - Started process (PID=10136) to work on /opt/airflow/dags/user1.py
[2022-08-28 11:29:25,253] {processor.py:641} INFO - Processing file /opt/airflow/dags/user1.py for tasks to queue
[2022-08-28 11:29:25,254] {logging_mixin.py:115} INFO - [2022-08-28 11:29:25,254] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/user1.py
[2022-08-28 11:29:25,274] {logging_mixin.py:115} INFO - [2022-08-28 11:29:25,271] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/user1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user1.py", line 18, in <module>
    '''
TypeError: 'module' object is not callable
[2022-08-28 11:29:25,275] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/user1.py
[2022-08-28 11:29:25,318] {processor.py:161} INFO - Processing /opt/airflow/dags/user1.py took 0.074 seconds
[2022-08-28 11:29:55,393] {processor.py:153} INFO - Started process (PID=10187) to work on /opt/airflow/dags/user1.py
[2022-08-28 11:29:55,417] {processor.py:641} INFO - Processing file /opt/airflow/dags/user1.py for tasks to queue
[2022-08-28 11:29:55,418] {logging_mixin.py:115} INFO - [2022-08-28 11:29:55,418] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/user1.py
[2022-08-28 11:29:55,435] {logging_mixin.py:115} INFO - [2022-08-28 11:29:55,433] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/user1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user1.py", line 18, in <module>
    '''
TypeError: 'module' object is not callable
[2022-08-28 11:29:55,435] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/user1.py
[2022-08-28 11:29:55,507] {processor.py:161} INFO - Processing /opt/airflow/dags/user1.py took 0.121 seconds
[2022-08-28 11:30:25,671] {processor.py:153} INFO - Started process (PID=10245) to work on /opt/airflow/dags/user1.py
[2022-08-28 11:30:25,672] {processor.py:641} INFO - Processing file /opt/airflow/dags/user1.py for tasks to queue
[2022-08-28 11:30:25,673] {logging_mixin.py:115} INFO - [2022-08-28 11:30:25,673] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/user1.py
[2022-08-28 11:30:25,690] {logging_mixin.py:115} INFO - [2022-08-28 11:30:25,689] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/user1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user1.py", line 18, in <module>
    '''
TypeError: 'module' object is not callable
[2022-08-28 11:30:25,691] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/user1.py
[2022-08-28 11:30:25,726] {processor.py:161} INFO - Processing /opt/airflow/dags/user1.py took 0.061 seconds
[2022-08-28 11:30:55,974] {processor.py:153} INFO - Started process (PID=10293) to work on /opt/airflow/dags/user1.py
[2022-08-28 11:30:55,997] {processor.py:641} INFO - Processing file /opt/airflow/dags/user1.py for tasks to queue
[2022-08-28 11:30:55,998] {logging_mixin.py:115} INFO - [2022-08-28 11:30:55,998] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/user1.py
[2022-08-28 11:30:56,016] {logging_mixin.py:115} INFO - [2022-08-28 11:30:56,013] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/user1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user1.py", line 18, in <module>
    '''
TypeError: 'module' object is not callable
[2022-08-28 11:30:56,016] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/user1.py
[2022-08-28 11:30:56,054] {processor.py:161} INFO - Processing /opt/airflow/dags/user1.py took 0.087 seconds
[2022-08-28 11:31:26,357] {processor.py:153} INFO - Started process (PID=10353) to work on /opt/airflow/dags/user1.py
[2022-08-28 11:31:26,358] {processor.py:641} INFO - Processing file /opt/airflow/dags/user1.py for tasks to queue
[2022-08-28 11:31:26,359] {logging_mixin.py:115} INFO - [2022-08-28 11:31:26,359] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/user1.py
[2022-08-28 11:31:26,374] {logging_mixin.py:115} INFO - [2022-08-28 11:31:26,372] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/user1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user1.py", line 18, in <module>
    '''
TypeError: 'module' object is not callable
[2022-08-28 11:31:26,374] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/user1.py
[2022-08-28 11:31:26,409] {processor.py:161} INFO - Processing /opt/airflow/dags/user1.py took 0.058 seconds
[2022-08-28 11:31:56,846] {processor.py:153} INFO - Started process (PID=10412) to work on /opt/airflow/dags/user1.py
[2022-08-28 11:31:56,848] {processor.py:641} INFO - Processing file /opt/airflow/dags/user1.py for tasks to queue
[2022-08-28 11:31:56,849] {logging_mixin.py:115} INFO - [2022-08-28 11:31:56,848] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/user1.py
[2022-08-28 11:31:56,866] {logging_mixin.py:115} INFO - [2022-08-28 11:31:56,864] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/user1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user1.py", line 18, in <module>
    '''
TypeError: 'module' object is not callable
[2022-08-28 11:31:56,866] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/user1.py
[2022-08-28 11:31:56,902] {processor.py:161} INFO - Processing /opt/airflow/dags/user1.py took 0.063 seconds
[2022-08-28 11:32:27,844] {processor.py:153} INFO - Started process (PID=10468) to work on /opt/airflow/dags/user1.py
[2022-08-28 11:32:27,861] {processor.py:641} INFO - Processing file /opt/airflow/dags/user1.py for tasks to queue
[2022-08-28 11:32:27,862] {logging_mixin.py:115} INFO - [2022-08-28 11:32:27,861] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/user1.py
[2022-08-28 11:32:27,876] {logging_mixin.py:115} INFO - [2022-08-28 11:32:27,874] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/user1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user1.py", line 18, in <module>
    '''
TypeError: 'module' object is not callable
[2022-08-28 11:32:27,876] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/user1.py
[2022-08-28 11:32:27,933] {processor.py:161} INFO - Processing /opt/airflow/dags/user1.py took 0.097 seconds
[2022-08-28 11:32:58,629] {processor.py:153} INFO - Started process (PID=10529) to work on /opt/airflow/dags/user1.py
[2022-08-28 11:32:58,633] {processor.py:641} INFO - Processing file /opt/airflow/dags/user1.py for tasks to queue
[2022-08-28 11:32:58,634] {logging_mixin.py:115} INFO - [2022-08-28 11:32:58,634] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/user1.py
[2022-08-28 11:32:58,649] {logging_mixin.py:115} INFO - [2022-08-28 11:32:58,647] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/user1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user1.py", line 18, in <module>
    '''
TypeError: 'module' object is not callable
[2022-08-28 11:32:58,649] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/user1.py
[2022-08-28 11:32:58,678] {processor.py:161} INFO - Processing /opt/airflow/dags/user1.py took 0.057 seconds
[2022-08-28 11:33:28,723] {processor.py:153} INFO - Started process (PID=10581) to work on /opt/airflow/dags/user1.py
[2022-08-28 11:33:28,723] {processor.py:641} INFO - Processing file /opt/airflow/dags/user1.py for tasks to queue
[2022-08-28 11:33:28,724] {logging_mixin.py:115} INFO - [2022-08-28 11:33:28,724] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/user1.py
[2022-08-28 11:33:28,738] {logging_mixin.py:115} INFO - [2022-08-28 11:33:28,737] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/user1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user1.py", line 18, in <module>
    '''
TypeError: 'module' object is not callable
[2022-08-28 11:33:28,738] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/user1.py
[2022-08-28 11:33:28,766] {processor.py:161} INFO - Processing /opt/airflow/dags/user1.py took 0.050 seconds
[2022-08-28 11:33:58,912] {processor.py:153} INFO - Started process (PID=10642) to work on /opt/airflow/dags/user1.py
[2022-08-28 11:33:58,923] {processor.py:641} INFO - Processing file /opt/airflow/dags/user1.py for tasks to queue
[2022-08-28 11:33:58,924] {logging_mixin.py:115} INFO - [2022-08-28 11:33:58,924] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/user1.py
[2022-08-28 11:33:58,951] {logging_mixin.py:115} INFO - [2022-08-28 11:33:58,950] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/user1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user1.py", line 18, in <module>
    '''
TypeError: 'module' object is not callable
[2022-08-28 11:33:58,952] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/user1.py
[2022-08-28 11:33:58,988] {processor.py:161} INFO - Processing /opt/airflow/dags/user1.py took 0.098 seconds
[2022-08-28 11:34:29,052] {processor.py:153} INFO - Started process (PID=10695) to work on /opt/airflow/dags/user1.py
[2022-08-28 11:34:29,053] {processor.py:641} INFO - Processing file /opt/airflow/dags/user1.py for tasks to queue
[2022-08-28 11:34:29,054] {logging_mixin.py:115} INFO - [2022-08-28 11:34:29,053] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/user1.py
[2022-08-28 11:34:29,068] {logging_mixin.py:115} INFO - [2022-08-28 11:34:29,067] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/user1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user1.py", line 18, in <module>
    '''
TypeError: 'module' object is not callable
[2022-08-28 11:34:29,068] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/user1.py
[2022-08-28 11:34:29,096] {processor.py:161} INFO - Processing /opt/airflow/dags/user1.py took 0.049 seconds
[2022-08-28 11:34:59,569] {processor.py:153} INFO - Started process (PID=10748) to work on /opt/airflow/dags/user1.py
[2022-08-28 11:34:59,571] {processor.py:641} INFO - Processing file /opt/airflow/dags/user1.py for tasks to queue
[2022-08-28 11:34:59,572] {logging_mixin.py:115} INFO - [2022-08-28 11:34:59,572] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/user1.py
[2022-08-28 11:34:59,586] {logging_mixin.py:115} INFO - [2022-08-28 11:34:59,585] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/user1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user1.py", line 18, in <module>
    '''
TypeError: 'module' object is not callable
[2022-08-28 11:34:59,586] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/user1.py
[2022-08-28 11:34:59,612] {processor.py:161} INFO - Processing /opt/airflow/dags/user1.py took 0.049 seconds
